### ISSUE TITLE
Vinyl music player crash

### ISSUE THREAD

**Issue by alangpraharja** [VinylMusicPlayer/VinylMusicPlayer#1002]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
I'm closing this issue since it lacks actionable information (describing the crash/the context leading to the error).

Dont hesitate to reopen with more info
