### ISSUE TITLE
建议增加启动后自动打开播放界面和调整播放界面歌词字体大小的功能~

### ISSUE THREAD

**Issue by 7mm** [VinylMusicPlayer/VinylMusicPlayer#1030]
1、目前启动app后可以进入播放列表，需要手动点一下才能进入播放界面，希望后续能增加一个直接进入播放界面的功能，会比较方便；
2、专辑封面显示歌词的字体大小，希望后续可以有选项进行自定义，以便配合不同的播放设备。

很好的app，一直在用，感谢！

**Comment by soncaokim** [comment]
Please write in English
