### ISSUE TITLE
FLAC: Error adding cover album

### ISSUE THREAD

**Issue by springerspaniel23** [VinylMusicPlayer/VinylMusicPlayer#1055]
When you try to add a cover album from option >> Edit Tag >> Download from Last.fm and press the floppy icon the app crash
This happend with flac files. With mp3 files no problem.

 - Device: Motorola G84
 - Android Version: 14
 - Vinyl Music Player Version: 1.10.1

**Comment by soncaokim** [comment]
Duplicate of #891
