### ISSUE TITLE
Random crash on opening 

### ISSUE THREAD

**Issue by daishishi** [VinylMusicPlayer/VinylMusicPlayer#1059]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Close as incomplete

**Comment by daishishi** [comment]
Didn't check the report when I sent it (the automatic sent report on crash). This happened after an Android OS update, I believe it messed up the file access permission.
I cleared the cache / app data, after reopening Vinyl asked for permissions again. Upon allowing it the app functioned normally.
