### ISSUE TITLE
support for Tageditor in android 11

### ISSUE THREAD

**Issue by pawaom** [VinylMusicPlayer/VinylMusicPlayer#543]
Android 11 requires the `Storage access with Android 11` according to this 

https://www.youtube.com/watch?v=RjyYCUW-9tY

soon in android 12 there will be no support for `requestLegacyExternalStorage `

I have come across this code

https://github.com/RetroMusicPlayer/RetroMusicPlayer/blob/350cba204226f62bc54936ae514296bd44a04388/app/src/main/java/code/name/monkey/retromusic/activities/tageditor/AbsTagEditorActivity.kt

 which is similar to VinylMusicPlayer code however its in kotlin I have no experience with koltin can you provide example in java

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
Unstale

**Comment by ShareASmile** [comment]
.

**Comment by soncaokim** [comment]
Should be fixed with the latest release (1.5.3 and after)
