### ISSUE TITLE
Ignore "the" when sorting

### ISSUE THREAD

**Issue by strider72** [VinylMusicPlayer/VinylMusicPlayer#581]
When looking at the Artist list, half my catalog is under T because so many group names begin with "The ".

Sorting should ignore "The ".  The Who should be under W. They Might Be Giants should still be under T, so pay attention to the space!

**Comment by strider72** [comment]
Also watch out for The The. Only ignore at the start of the string ;-)

**Comment by strider72** [comment]
Yes, people can always manually go through thousands of tracks and rename them to somethibg they're not to overcome a limitation of a particular piece if software. Or the software can implement an extremely common sorting scheme.

Also: "a ", although I don't know a ton of bands that start with the indefinite article

**Comment by strider72** [comment]
Sorry to see this got no traction. It seems a really obvious feature to me

**Comment by soncaokim** [comment]
Fixed by https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/630
