### ISSUE TITLE
[Android 12] Icon will not show on "Status-Bar"

### ISSUE THREAD

**Issue by xkeyscore59** [VinylMusicPlayer/VinylMusicPlayer#622]
I noticed that on Android 12 the Icon will not show on the status-bar. It does in fact show in the notification Area when you swipe down.

> Steps to reproduce the behavior:
1. Install VinylMusicPlayer on Android 12
2. Open the App 
3. Start playing a song 

**Expected behavior**
Icon shows fine

 - Device: Samsung Galaxy S10
 - Android Version: 12 OneUI 4.1
 - ROM: Stock
 - Vinyl Music Player Version: 1.3.0 (Fdroid)

**Additional context**
This bug can be resolved by activating the "Classic notification Design" option.
![Screenshot_20221030-194040_Vinyl Music Player](https://user-images.githubusercontent.com/117037165/198895867-a3c4164f-e8d8-4736-b3c7-bf4bb899bb3c.jpg)
![Screenshot_20221030-194029_Vinyl Music Player](https://user-images.githubusercontent.com/117037165/198895869-cb36cb1c-93d5-4b7a-bc2c-1da91d5d098c.jpg)

**Comment by soncaokim** [comment]
This is linked to the Ndroid 12+ behaviour - intercepting and replacing the app's notification by system's one
