### ISSUE TITLE
Cannot browse SD card

### ISSUE THREAD

**Issue by CedFel** [VinylMusicPlayer/VinylMusicPlayer#626]
**Description**
Either in the library whitelist and blacklist settings or in the folder view, Vinyl cannot browse a path "above" /storage/emulated/0/

**Steps to reproduce the behavior**
1. Open the folder view or go to settings>Library>blacklist (or whitelist)
2. Go one or several levels up until you reach /storage/emulated/ or above
3. Vinyl shows this directory as empty, thus it's impossible to go to the SD card which is something like /storage/emulated_/XXXX-XXX/_

**Smartphone**
- Device: Samsung Galaxy A40
- Android 11
- Vinyl Music Player Version: 1.3.0

**Comment by Avispa** [comment]
Here for reporting the same problem.
Was fine on _Android 9_ but broken on _Android 13_ though I granted all possible permissions to _Vinyl_.

**Comment by Fecfec97** [comment]
To add, also suffering this same issue, it effects whitelist, blacklist and folder view.

Is there not a way to address this issue by using the built in folder select as that has permissions to browse these folder by default?

**Comment by mirenbz** [comment]
Same here, on Android 13. It does read files from SD card on blacklist mode, but browsing there does not work. It's all or nothing right now forbthe SD card, either:

- blacklist mode, SD files read and added to library, unable to add SD folders to blacklist (all)
- whitelist mode, unable to add an SD folder (nothing)

Any clues of progress to fix this? Thanks!

**Comment by michaelc-xyz** [comment]
I would like to report this issue as well. Moto G Fast, Android 11 (LineageOS 18.1), Vinyl 1.5.2

**Comment by arfelo1** [comment]
Same issue here. POCO X3 NFC with MIUI 14.0.5, Vynil1.5.4

**Comment by michaelc-xyz** [comment]
I am still having this problem.  
Not sure if I should open a new issue, but I'll post here first, just in case.  

Unihertz Jelly Star
Android 13 (LineageOS 20 GSI)
Vinyl Music Player 1.5.6

**Comment by n2burns** [comment]
Do you not have the SD Card option in your sidebar? This is a screenshot from my Samsung Galaxy S10e on Android 12:
![Screenshot_20231113-210953_Vinyl Music Player](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/431090/53419a95-1f6c-405c-b9ca-78581e6fd26a)

**Comment by michaelc-xyz** [comment]
I can browse the SD card via the sidebar option, but when I try to navigate to it in the blacklist menu the levels above `/storage/emulated/0/` show as empty

![Screenshot_20231114-023119_Vinyl Music Player](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/4443102/c02f30f7-d7d0-4fbb-b315-1c25a18c2f31)
