### ISSUE TITLE
[CRASH] NoClassDefFoundError: java.nio.charset.StandardCharsets on Android 4.2

### ISSUE THREAD

**Issue by ildar** [VinylMusicPlayer/VinylMusicPlayer#636]
The search [says](https://stackoverflow.com/questions/38183027/java-lang-noclassdeffounderror-java-nio-charset-standardcharsets) StandardCharsets are at APIs >= 19.

**Comment by soncaokim** [comment]
Thanks for investigating.

The usage of StandardCharset is very likely coming from an external library that we dont control (jaudiotagger, for ID3 tags readinf and editing).

The most likely resolution for this crash would then be to drop Android <19 support.

**Comment by ildar** [comment]
I'd rather prefer with killing ID3 editing then raising minSDK. :-\

**Comment by soncaokim** [comment]
> I'd rather prefer with killing ID3 editing then raising minSDK. :-\

This JAudioTagger lib is necessary for tag reading as well, ie. for the *basic operations* of this app + some "advanced" features like tag editing, replay gain, multi-artists support...

I've stopped relying on the Android's native ID3 support - it's buggy.

**Comment by ildar** [comment]
Also a workaround some people use:
https://bitbucket.org/ijabz/jaudiotagger/issues/188/nullpointerexception-when-committing#comment-33860656

**Comment by soncaokim** [comment]
@ildar I'm sorry but I dont see any positive and reliable outcome for this - either from upstream or doing patching here.
More over, the minimum SDK version will be upgraded to 19 anyway (due to other dependencies) -> Closing this as 'wont fix'
