### ISSUE TITLE
Repeat album button switches off

### ISSUE THREAD

**Issue by aikobel1** [VinylMusicPlayer/VinylMusicPlayer#663]
The repeat album button switches back to inactive during play; would be great if it could remain active by default on all albums.

Device info:
---
<table>
<tr><td>App version</td><td>1.4.0</td></tr>
<tr><td>App version code</td><td>178</td></tr>
<tr><td>Android build version</td><td>J510FNXXU2BRE6</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.J510FNXXU2BRE6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j5xnlte</td></tr>
<tr><td>Device model</td><td>SM-J510FN</td></tr>
<tr><td>Device product name</td><td>j5xnltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by ronsn** [comment]
Yes, I can confirm that the "Repeat all" and "Repeat one" functionality is disabled when the player will be used after a few hours of not using the player.
Player version: 1.4.0
Phone: Nokia 5.3
Android version: 11
Installed by: F-Droid store

**Comment by xdarklight** [comment]
I can confirm this on version 1.5.0
It did work on version 1.3.0 though

**Comment by toolstack** [comment]
This annoyed me enough to track down, I've submitted PR #811 to resolve it.
