### ISSUE TITLE
Unable to start M3U playlists in Android Auto

### ISSUE THREAD

**Issue by BOB74j** [VinylMusicPlayer/VinylMusicPlayer#671]
Non-default playlists cannot be started through the Android Auto interface. Possibly related to #544 

Opening a playlist and selecting any track therein via Android Auto briefly flashes the error "Vinyl Music Player doesn't seem to be working right now" without queuing any tracks.

**Steps to reproduce the behavior**
1. Connect device to car and open Android Auto
2. Open Vinyl Music Player from within Android Auto
3. Select any non-default playlist
4. Select any track within the playlist
5. No tracks will be queued. An error message is briefly displayed: "Vinyl Music Player doesn't seem to be working right now."

**Expected behavior**
Selecting a playlist entry in Android Auto should properly queue the playlist starting from the selected track. Alternatively, similar to the AA behavior for albums, selecting a playlist should queue the list from the beginning.

**Device info**
 - Device: Motorola Moto G5 Plus / Honda OEM head unit
 - RAM: 4 GB
 - Android Version: 10
 - ROM: Pixel Experience 10+
 - Vinyl Music Player Version: 1.4.0.178 (the same bug has been confirmed on versions 1.3.0.177 and 1.2.0.176)

Relevant Packages:
Vinyl Music Player: 1.4.0
Google Play services: 23.03.13 (100400-503260631)
Google: 13.48.11.29.arm64
Android Auto: 8.6.625054-release

AA Permissions:
phone: on
contacts: on
location: on
sms: on
microphone: on
calendar: on
call_log: on
nearby_devices: off

**Additional context**
My playlists are saved as .M3U files in the same internal storage directory as my music files. Interestingly, the default, built-in playlists (last added, history, top tracks) appear unaffected by this bug. Starting a queue in AA from an album, song, artist, or genre also behaves as expected.

M3U playlists can still be queued from standard Vinyl app interface and this queue will persist upon starting Android Auto. However, starting M3U playlists from the AA interface directly is broken.

The error message which appears is identical to the one shown in the screenshot in issue #544

**Comment by GraphicHealer** [comment]
I have had this issue as well.
