### ISSUE TITLE
Abnormal intra-letter alphabetical sorting in v1.4.1 previous version v1.4.0 not affected

### ISSUE THREAD

**Issue by bryanparadis** [VinylMusicPlayer/VinylMusicPlayer#685]
**Describe the bug**
Alphabetical sorting of Artists is broken within a letter. See screenshot for example,

**To reproduce**
Open v1.4.1 app and the sorting is wrong

**Expected behavior**
Intra-letter

**Device info**
 - Device: LG G8X 
 - Android Version: 12
 - ROM: Stock
 - Vinyl Music Player Version: v1.4.1 (downgraded to v1.4.0 and bug not present)

**Additional context**
I would assume it is related to: https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/630

**Screenshot example**
![Screenshot_20230207-204507](https://user-images.githubusercontent.com/2258437/217448130-a4695601-7493-425e-8455-28bad26286db.png)

**Comment by soncaokim** [comment]
Hmm thanks for reporting this. I can confirm the bug.

**Comment by soncaokim** [comment]
I dont think this is solely linked to https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/630.

**Comment by bryanparadis** [comment]
Thanks!
