### ISSUE TITLE
FLAC artwork editing causes crashes

### ISSUE THREAD

**Issue by crunchymuffins** [VinylMusicPlayer/VinylMusicPlayer#690]
This issue still exists #437

**Comment by soncaokim** [comment]
Can you please precise which format of data (it was FLAC in the original report).

If possible, attach a sample file and steps that can help us to reproduce.

**Comment by crunchymuffins** [comment]
Sorry for the delayed reply,

>Can you please precise which format of data (it was FLAC in the original report).

I have experienced crashes with only FLAC files so far.

Steps to reproduce: 

1. Open any album containing FLAC files
2. Press on the three dots 
3. Press `Tag Editor`
4. Click on the album image
5. Change the Image either by pressing `Download from last.fm` or `Pick from local storage` 
6. Press save. The App will crash and the album cover won't be updated 

> If possible, attach a sample file

Github doesn't support .flac file uploads unfortunately :c

also thank you for your all your effort in improving Vinyl C:

(also i was in a rush typing this, so sorry if anything doesn't make sense C:)

**Comment by crunchymuffins** [comment]
Oh alright, 

should I report this issue to upstream?

**Comment by soncaokim** [comment]
Closing this issue. Cannot be resolved within the app.
