### ISSUE TITLE
Coloured Up Next Text on Dark/Black Modes

### ISSUE THREAD

**Issue by Sai-P** [VinylMusicPlayer/VinylMusicPlayer#701]
**Is your feature request related to a problem? Please describe.**
A pet peeve I've always had with Phonograoh that nobody seems to have remedied ever is the Up Next text in the queue having a disparity between the Light and Dark/Black themes.

**Describe the solution you'd like**
I would like to see the Up Next text to be coloured on Dark/Black themes to match that of the Light Theme

**Describe alternatives you've considered**
None.

**Additional context**
Here are screenshots to show the current state of affairs regarding this.

[Light Theme](https://photos.app.goo.gl/dtHdE8zCC6pmSMJr9)

[Dark/Black Theme](https://photos.app.goo.gl/bHBvvmtskqyVYqoL7)

**Comment by Sai-P** [comment]
Ok the screenshots didn't get added as I wanted it to so I've actually added them below this time.

[Light Theme](https://photos.app.goo.gl/UiYYRsZaXuQhVCjy6)

[Dark/Black Theme Currently](https://photos.app.goo.gl/GHmU7THLQw3a3Lo47)

**Comment by soncaokim** [comment]
Fyi, the links lead to a "Album is empty" page.

**Comment by Sai-P** [comment]
Hmm idk what's up, let me try fixing the links.

**Comment by Sai-P** [comment]
Ok, I have edited the links in the original post and have verified that they actually work, thanks for letting me know 👍

**Comment by Octoton** [comment]
In dark theme doing that can give strange visual result:
![Screenshot_20230307-222624](https://user-images.githubusercontent.com/56130419/223557192-830b6d77-f038-462c-b39a-89b806304b40.png)
![Screenshot_20230307-222614](https://user-images.githubusercontent.com/56130419/223557197-8a5afa5c-5637-4a7d-9937-277a94c407f5.png)

Seems like to do this, we will need a utility to manage color clarity, will need to look into what android api have for this

**Comment by Octoton** [comment]
Tried some contrast change and gotten:
![Screenshot_20230307-231659](https://user-images.githubusercontent.com/56130419/223566882-998fd0fc-4c12-4ce6-834b-7638046c9ed5.png)

Do you think this would be good to resolve the disparity ?

**Comment by Sai-P** [comment]
I think it looks great

**Comment by Octoton** [comment]
Ok, still need to correct some stuff in my mockup
but after that I will do a PR for this
