### ISSUE TITLE
Ability to play (replace current playlist) by default

### ISSUE THREAD

**Issue by ajgelado** [VinylMusicPlayer/VinylMusicPlayer#712]
In most media player apps, when you select a new track or album, the current playlist stops playing and the selected one starts immediately. Vinyl worked that way up to version 1.4.1. Starting in version 1.5.0, when you select a track, you get a pop-up asking you if you want to play it or enqueue it, even if the player is paused or current playlist has ended.

My suggestion is twofold:

1. If the player is paused or current playlist has ended, start playing immediately. It is absurd to enqueue to a finished playlist and then having to navigate through the list to the now playing screen and press play!

2. In the case that a song is playing, many people (me included) would prefer to completely replace the current playlist, so it would be nice to have a global option to disable the pop-up and always start playing the track (basically, the previous version's behaviour).

Alternatively, I think another option would be to restore completely the behaviour of v1.4.1 (that is, always playing immediately), and give access to the enqueue function via a long press and/or the track context menu. Usability-wise, this would make a lot of sense: in a personal player, it is much more frequent selecting a track than adding it to a playlist.

The main reason why I do love Vinyl is because it's nice and simple, yet full-featured. This change has made a lot more complex one of the most frequent actions in Vinyl, changing tracks. When you are walking in the street and the current album or playlist ends, the least you need is having to navigate through several menus and screens to play the next album or list. Please solve this, either using my suggestions or other user's ideas.

**Comment by brianzable** [comment]
I second this. I find the new behavior confusing. I'd be in favor of a setting to turn it off. When I click a song I just want it to play.
