### ISSUE TITLE
Use #Playlist field for playlist name

### ISSUE THREAD

**Issue by ghbrown** [VinylMusicPlayer/VinylMusicPlayer#718]
I'd like to use the playlist name baked into `.m3u` files to title the playlist in Vinyl. Perhaps something is wrong on my end, but currently Vinyl is using the file name of the `.m3u` file instead of the value of the `#PLAYLIST` field.

**Comment by soncaokim** [comment]
As it is right now, the app relies on Android MediaStore facility to deal with m3u files.
i.e. your request cannot be handled with this app.

**Comment by ghbrown** [comment]
No problem, thanks for getting back to me.

For future readers of this thread, it does appear that the `.m3u` file name is the one and only source for the name of the playlist displayed in Vinyl, and when one creates a playlist using Vinyl there is no included `#PLAYLIST` field in the `.m3u`.
