### ISSUE TITLE
Android 12/ Title Freeze 

### ISSUE THREAD

**Issue by IAlwayWasALoser** [VinylMusicPlayer/VinylMusicPlayer#719]
**Describe the bug**
Title of the song on the pin notification area freeze when it move the new song.
**Device info**
 - Device: Redmi Note 11s
 - Android Version:12
 - ROM: 13.0.7 SKEMIXM
 - Vinyl Music Player Version: 
1.5..0

**Comment by soncaokim** [comment]
Closing this, duplicate of #732
