### ISSUE TITLE
Google Play version outdated

### ISSUE THREAD

**Issue by Schoumi** [VinylMusicPlayer/VinylMusicPlayer#731]
Hi, 

Is it normal that the last version on the Play Store is the 1.3.0? This version seems to be uninstallable on recent device.

thanks for your work

**Comment by leo-unglaub** [comment]
Same problem on my Fairphone 3 with the latest Android 11

**Comment by AdrienPoupa** [comment]
I published the newest release to the Play Store, it will be available after review. I also added CI/CD support for Play Store publication so this won't happen again.
