### ISSUE TITLE
Wrong track title in the notification after pressing next

### ISSUE THREAD

**Issue by jneidel** [VinylMusicPlayer/VinylMusicPlayer#732]
**Observed behavior**

The notification is showing the wrong track title (the previous song.)

<img width=150 src="https://user-images.githubusercontent.com/25589715/229539270-991806e8-703d-4f42-bd42-4c2061103a9e.jpeg"/> <img width=150 src="https://user-images.githubusercontent.com/25589715/229539274-d067aaa2-1f42-48d1-a5c6-9428a83c1a16.jpeg"/> <img width=150 src="https://user-images.githubusercontent.com/25589715/229542020-36d15e54-969d-412a-84b6-afd719d1626a.jpeg"/> <img width=150 src="https://user-images.githubusercontent.com/25589715/229542003-a8b26d3f-a6e7-4d64-9e8d-e1fc2803efec.jpeg"/>

**To reproduce**
1. Play an album. Press next either in notification or in player. Sometimes the notification will not update and still show the previous song title.
2.  Play an album. `Delete from device` the currently playing song. The notification will not update and still show the deleted song title.

**Expected behavior**
Up-to date track title in notification.

The progress in the notification and is not affected. Pausing will fix the notification to show the correct song again.

**Device info**

 - Device: Samsung S21
 - Android Version: 13
 - ROM: Rooted Stock Samsung
 - Vinyl Music Player Version: 1.5.0

---

Thanks for the effort you're putting into Vinyl! Have been using it for a few years and it has always served me well :smile:

**Comment by jneidel** [comment]
Possibly the same as #719

**Comment by soncaokim** [comment]
Closing this in favor of #631
