### ISSUE TITLE
Enable setting a default when choosing Play / Play next / Add to playing queue

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [VinylMusicPlayer/VinylMusicPlayer#741]
**Is your feature request related to a problem? Please describe.**
When I want to listen to an album, I am asked to choose between Play / Play next / Add to playing queue. I choose play every single time, I never find myself using the other options.

**Describe the solution you'd like**
I would like to be able to set a default for this dialogue, so I don't have to choose every time I start a new album.

**Describe alternatives you've considered**
I've considered not submitting an issue since it is just a small annoyance.

**Additional context**
I think this used to work that way in earlier versions of vinyl, but I can't check since I updated.

**Comment by soncaokim** [comment]
Can you please check what is the version of the app you are using? This should be fixed in v1.5, where there is a setting to choose the default action.

**Comment by pokemonpasta** [comment]
Not the OP but I'm on 1.5 and if this setting to choose a default exists I can't find it.

**Comment by soncaokim** [comment]
Yep, sorry for that. The fix has been committed to master but not released.

**Comment by soncaokim** [comment]
I'm pushing a new 1.5.1 version containing the needed change. This will be available on F-Droid as soon as the bot picks  it up. On G-Play store this will take longer time (there are blockers that we are working on).

Regards
