### ISSUE TITLE
Any Developement happening?

### ISSUE THREAD

**Issue by GrittyH** [VinylMusicPlayer/VinylMusicPlayer#744]
Hello, this is a great project but it would be great if some updates are made, eg: wen you click on the aong that it doesn't allways ask you if it plays it or if it adds it to playlist etc.
I have seen that this is already worked on(even done?) but no compiled update is comming. 

I can understand that there is no time but 3 months? I would be more than happy to buy the Devs a cafee or two as motivation when possible, what's the easiest way to do that?

**Comment by AdrienPoupa** [comment]
Hello! The easiest way to make it happening is to contribute yourself, open a PR and I am sure it will be reviewed and merged :) Otherwise, you may report bugs here. Thank you!
