### ISSUE TITLE
Playlists sometimes show "0 Songs" and "Empty playlist" though they really still have their songs

### ISSUE THREAD

**Issue by Pazu** [VinylMusicPlayer/VinylMusicPlayer#745]
**The bug**
Sometimes playlists lose track of their contents, though the contents does sort of still seem actually to be there

**To reproduce**
1. Create a playlist
2. Add some songs
3. At some point (not sure yet what steps are necessary to get to this point) the playlist will show "0 Songs' underneath and "Empty playlist" inside
4. If you started playing the playlist before that, you can continue to play and the songs you added will play
5. If you add one new song to the list you'll be able to see all the other songs once again.

**Expected behavior**
Playlist content should always be visible.

**Device info**

 - Device: Sony Xperia XZ2 Compact
 - Android Version: 12
 - ROM: /e/OS 1.11
 - Vinyl Music Player Version: 1.5.0

**Comment by soncaokim** [comment]
Close as related to #965
