### ISSUE TITLE
"You're about to add XXX songs to Playlist" dialog popup is offscreen

### ISSUE THREAD

**Issue by donttasemebro** [VinylMusicPlayer/VinylMusicPlayer#749]
I use Vinyl on a windows machine and an android phone with little problems I can't use workarounds for. However, when I use it on an Android 10 Tablet Car Stereo there is a bug that breaks the app I'll try to describe below.

When I first started using Vinyl I noticed Playlists did not work so I began sorting songs by Genre which ended up being far more useful now I can't live without it.

To recreate problem:
1. Go to Genre tab and select any of the Genres which adds them to a playlist.
2. If I want to select a different Genre I press back button twice and select a different Genre.
3. At this point it gives a popup Dialog Box that says "You are about to add XXX songs to Playlist would you like to continue" or something like that.
4. The problem is the Yes and No buttons are at the bottom off the screen and can't be clicked on so I can't select anything meaning I have no way to move around my music collection.

Would there be any way to make that Dialog Box Free Floating or Center it instead? Maybe an option in settings to turn off the confirm add popup?

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Joying Car Stereo
 - Android Version 10 about to be 11
 - It is a proprietary Joying OS but it's backend is obviously Android 10
 - Vinyl Music Player Version: 1.5.0

**Comment by soncaokim** [comment]
Hi, is this still a problem with the latest release?
There was a change (https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/765) that might fix the issue you described

**Comment by soncaokim** [comment]
Assume as fixed (see comment above)
