### ISSUE TITLE
Queueing that does not replace the whole queue

### ISSUE THREAD

**Issue by Cwpute** [VinylMusicPlayer/VinylMusicPlayer#755]
**Is your feature request related to a problem? Please describe.**
I often find myself listenning to a full album/playlist vhen suddenly i have the urge to listen to one song that isn't part of this playlist. So i search in the app albums, but when i tap on that song the whole queue is replaced with the album/folder the song was accessed from.

**Describe the solution you'd like**
I'd like to have another Queueing option that:
1. adds the song i tapped on right after the currently playing one in the queue
2. immediately play that next song i requested

**Comment by soncaokim** [comment]
On the search result, you can click on the dots menu next to the song to play it next/insert next to the queue/add to end of queue

**Comment by Cwpute** [comment]
This is not exactly what i ask for, as it the curently playing song would still be playing after that actiwn. I'd then have to manually press the Next button for that song i chose to play, or wait for the curent song to end.
