### ISSUE TITLE
Understanding the new ReplayGain feature

### ISSUE THREAD

**Issue by IOI-655321** [VinylMusicPlayer/VinylMusicPlayer#76]
Sorry if im being dumb but I just wanted to check, the new replaygain feature is this an automatic normalisation of all audio or do we have to change something in the settings for it to make it work?

Ive read about replaygain before but generally in apps where theres been volume normalisation its just been a tickbox to turn it on or off.

**Comment by AdrienPoupa** [comment]
Hi,

There are indeed two new settings:
* The ReplayGain source mode: None (disables the feature, by default), Track and Album
* The ReplayGain preamp, where you can tweak the ReplayGain volume

@knacky34 could probably explain it better than I am.

**Comment by knacky34** [comment]
Hi @IOI-655321 to make the replaygain works you must add replaygain infos to songs, you can use for example [MP3Gain](http://mp3gain.sourceforge.net/), or [Foobar2000](http://www.foobar2000.org/) to that

and you need to set replaygain source mode to :
- track : makes all songs at the same loudness
- album : same as track but it keep the album dynamics

**Comment by IOI-655321** [comment]
Ok so Ive been using MP3Gain for all my audio and ive set it to 'track' and so it should all just work now.  Ill give a few things a try and see how it goes!
