### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by monochromec** [VinylMusicPlayer/VinylMusicPlayer#770]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Closing this since it lacks detailed info
