### ISSUE TITLE
Play Store version out of date

### ISSUE THREAD

**Issue by GraphicHealer** [VinylMusicPlayer/VinylMusicPlayer#772]
The version of the app on the play store is only on version 1.3.0, which is rather out of date, by almost 2 years.

Can someone please update this? It's the only way I can have android auto compatibility. I use android auto daily, so this is rather annoying to be 2 years behind.

Thanks,
G

**Comment by mihawk90** [comment]
If only someone pinned #731 to the top of the issue page... oh wait.

**Comment by GraphicHealer** [comment]
Oh Sorry. Didn't see it.

**Comment by GraphicHealer** [comment]
> I published the newest release to the Play Store, it will be available after review. I also added CI/CD support for Play Store publication so this won't happen again.

Dude, you are awesome. Thanks so much!
