### ISSUE TITLE
Support for multiple genres using separator

### ISSUE THREAD

**Issue by kausar007** [VinylMusicPlayer/VinylMusicPlayer#773]
Support for multiple artists was implemented however the multiple genres was not implemented and yet the issue https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/70 was closed. 

Is it possible to add it?

**Comment by gaycodegal** [comment]
For context from the PR, the semicolon character `;` and newline character will be supported separation characters once this change is merged.
