### ISSUE TITLE
Vinyl Crash while trying to scan music folder

### ISSUE THREAD

**Issue by jsegraves99** [VinylMusicPlayer/VinylMusicPlayer#774]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Closing this now due to lack of details, please reopen it if you can provide with more info
