### ISSUE TITLE
Not in Android Auto app list

### ISSUE THREAD

**Issue by nerradtreborsniktaw** [VinylMusicPlayer/VinylMusicPlayer#775]
Vinyl: v1.5.2
AA: v10.2.633224
Miui 12, Android 11

Vinyl does not appear in the list of apps when I Customise the AA launder.

Any help appreciated.

**Comment by soncaokim** [comment]
I assume AA means Android Auto?
The 1.5.2 is not vetted by the G Playstore, so you need to enable the
developper mode in AA to make Vinyl visible.

**Comment by nerradtreborsniktaw** [comment]
Yes, Android Auto, apologies ;o)

Didn't know about Developer Mode so I'll give that a go.

Thanks

**Comment by nerradtreborsniktaw** [comment]
That worked, thanks.

For completeness lest someone else finds themselves here:
In Android Auto tap Version 10 times to enable developer mode
Tap overflow menu (top right) and enter developer settings
Set application mode to Developer
Tick Unknown Sources

**Comment by nerradtreborsniktaw** [comment]
Solution tested and working
