### ISSUE TITLE
ReplayGain default preamp

### ISSUE THREAD

**Issue by MageFroh** [VinylMusicPlayer/VinylMusicPlayer#785]
**Describe the bug**
I use replay gain for my music, and noticed that the volume of most songs was adjusted properly by Vinyl, but not all.
The problem disappears if the replay gain preamp is set to a large enough negative value.

**To reproduce**
1. Set up a music library that has song with both negative and positive replay gain values. It's easier if to notice when the replay gain is at least +/- 2dB.
2. Enable replay gain in the settings. Keep other settings to their default setting, such as the replay gain preamp (0dB).
3. Play the songs.
4. Compare the perceived volume with replay gain disabled.

**Expected behavior**
Songs with negative replay gain are made quieter by Vinyl.
Songs with positive replay gain are made louder by Vinyl - This is not the case when the replay gain preamp is at its default value (0dB).

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Nokia XR20
 - Android Version: 13
 - ROM: unknown
 - Vinyl Music Player Version: 1.5.2

**Additional context**
Looking at [the code](https://github.com/VinylMusicPlayer/VinylMusicPlayer/blob/9ff46f38a952ed4e2c5aceecf98e57070c09f56f/app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java#L907), there is a deviation from the [formula on the replay gain page](https://wiki.hydrogenaud.io/index.php?title=Replay_Gain_specification#Reduced_gain).
Instead of capping based on the peak amplitude, Vinyl caps at value 1 (so the volume is not increased as the result of replay gain).
I suppose this is because [Android's MediaPlayer class](https://developer.android.com/reference/android/media/MediaPlayer#setVolume(float,%20float)) only allows a volume adjustment in the range 0.0 to 1.0.

The adverse effect is that if a track has a positive replay gain value, then its replay gain is effectively not applied.
It's easy to fix: simply apply a negative replay gain preamp to all tracks. I changed the preamp to be negated value of the maximum replay gain of all my songs, that it seems to be OK now.

But maybe setting a value of 0dB by default is not the best, since Vinyl will only make songs quieter, but never louder? Maybe a default value of -3dB would be best? (Most of my songs seem to be below +2.7dB, but not sure that's a good enough sample!)
Alternatively, a little pop up or explanation around the replay gain settings could be helpful too (I did not initially understand the usefulness of the replay gain preamp setting).

**Comment by soncaokim** [comment]
Thanks for this report. I have that feeling too, but never got time to investigate/confirm the issue.

Looks like that you've had a good look at the code. Do you want to submit a PR to fix this?

**Comment by MageFroh** [comment]
Hi @soncaokim,

After looking a bit more into this, it looks like the best might be to use a [DynamicProcessing](https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing) audio effect to implement the replay gain, instead of volume: it seems to allow both positive and negative values on its input gain stage.
It requires API level 28, but we could fallback to the volume-based method when running on an old Android.

I'd have to double-check it is able to operate properly alongside the equalizer settings, but do you think it's an idea worth pursuing?

**Comment by soncaokim** [comment]
hello,

I've just browsed across the documentation link you provided. My first impression is that this might be interesting to study and eventually modernize the code base. 

Going back to your original comment - please correct me if I'm wrong:
- We'd scan the whole library to determine the lowest preamp value, and update that value on new track or any removal.
- Or have a negative preamp default value.

My personal opinion: either approach will be helpful to improve the app. My fear is that the DynProcessing approach is heavier to implement --> your call :-)

@AdrienPoupa do you have an opinion on this?

**Comment by MageFroh** [comment]
Hi @soncaokim - I was initially planning to simply set the default value of the preamp to a fixed -3dB value.
But that made me worried that it would make the songs too quiet for many people, so I've opened PR #828 that introduces DynamicsProcessing in MultiPlayer.
Let me know what you think - it seems to work, but feedback is welcome.

**Comment by soncaokim** [comment]
Fixed by #828
