### ISSUE TITLE
Regression: Folder blacklisting + .m3u loading not working

### ISSUE THREAD

**Issue by Robin-Sch** [VinylMusicPlayer/VinylMusicPlayer#822]
Version 1.5.4 (and 1.5.3) is already published on F-Droid, while it's a pre-release and not officially released. See https://f-droid.org/packages/com.poupa.vinylmusicplayer/

For me it wouldn't detect my .m3u files and therefore all my playlists broke. Also, when trying to select a folder under "blacklist" in settings I got an error that the app didn't have READ_MEDIA_AUDIO, while it had that permission.

I downgraded the app and both issues were resolved.

**Comment by secure-username** [comment]
I find that on any version past 1.5.2 (including the most recent pre-release 39b9b10) Vinyl will detect my .m3u files and list them in the Playlists tab, but almost all of them will be empty (show 0 songs). The ones that do have songs have only a small fraction of the number they are supposed to, and sometimes it's the same few songs repeated (I did not put any repeated songs in my playlists).

**Comment by soncaokim** [comment]
Close as related to #965
