### ISSUE TITLE
crashed while scanning for Songs

### ISSUE THREAD

**Issue by TheRootbearGuy** [VinylMusicPlayer/VinylMusicPlayer#854]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Closing this since it lacks actionable info. If you have more info, feel free to reopen this. Thanks
