### ISSUE TITLE
Support for language tag

### ISSUE THREAD

**Issue by orangecorn** [VinylMusicPlayer/VinylMusicPlayer#862]
I listen to music in 3 different languages, and up until now have just maintained a playlist for each language and one combined, but it is very tedious and annoying sometimes. 

My feature request is that support for language tag is added. I know it is probably a small amount oif the user base that would use it, so it would be a feature one would turn on in settings. Then when one opens the 'Tag Editor' on a song, 'Language' would be an extra option.

I considered using the 'Genre' tag, but that would mess things up on my computer. It would also look weird, having most played Genre as English instead of Pop or whatever it would be.

I think it would make the most sense to be placed above lyrics in the Tag Editor when enabled. It would also need to have support for multiple languages in the case of duets etc. 

Thanks!

**Comment by soncaokim** [comment]
Sorry, I dont think we'll merge and support such a feature - even with a toggle.
