### ISSUE TITLE
Tag editor is broken

### ISSUE THREAD

**Issue by MageFroh** [VinylMusicPlayer/VinylMusicPlayer#863]
**Describe the bug**
On Android 13, when clicking on Save in the tag editor, the editor behaves as if everything is saved, but in fact the file was not changed.

**To reproduce**
1. Use a recent Android (reproducible with 13)
2. Use the 3 dots on one of the songs -> "Tag editor"
3. A popup is shown: "Allow Vinyl Music Player to modify this audio file?". Tap "Allow".
4. Modify one of the fields
5. Click on the save button on the bottom right
6. Leave the editor using the arrow on the top left
7. Use the 3 dots on one of the songs -> "Details" or "Tag editor" (or use another app to inspect the tags of the audio file itself)
8. The field modified in step 4 still has the old value.

**Expected behavior**
The field modified in step 4 shows the new value.

**Device info**
 - Device: Android Studio Emulator or Nokia XR 20
 - Android Version: 13
 - ROM: Stock
 - Vinyl Music Player Version: 1.5.6

**Additional context**
I think with recent android version, the SD Card permission is not needed, and cannot be granted. The dialog shown at the start of the activity should be enough to allow write access to the media file.
It could also be argued that the permission dialog should only be shown when the user clicks on the save button, rather than at the time the activity is created.

**Comment by gaycodegal** [comment]
thanks for the info, I'll look into a single issue fix for the tag editor break, and then you can do the request-permission-on-write refactor if you wish after

**Comment by soncaokim** [comment]
Assume as fixed by #929
