### ISSUE TITLE
No longer playing any sound over internal or Bluetooth audio

### ISSUE THREAD

**Issue by theksepyro** [VinylMusicPlayer/VinylMusicPlayer#871]
**Describe the bug**
When attempting to listen to a song, no audio is played over either the devices internal speaker, or over a Bluetooth connection 

**To reproduce**
1. Open App
2. Navigate to and select any track to play
3. Listen for audio and hear nothing

**Expected behavior**
I Expect the selected song to play out of the speakers or over Bluetooth depending on the configuration.

**Device info**

App version: 1.6.0
App version code: 186
Android build version: 10817346
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231105.001
Device brand: google
Device manufacturer: Google
Device name: barbet
Device model: Pixel 5a
Device product name: barbet
Device hardware name: barbet
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**Additional context**
There was a moment it was working after a device restart but when I skipped to another track it stopped playing again, and hasn't worked again since. I would think it was a hardware issue, but my device will still play audio from any other apps I try without hitch.

I have attempted restarting the app, restarting the device, choosing tracks in a variety of formats (flac, mp3, ogg).

I'm using app version 1.6.0 from F-Droid
    
Edit: Downgrading to version 1.5.5 makes the issue stop for me

**Comment by soncaokim** [comment]
If possible, can you please test the pre-release version (available to download via this link https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/tag/pre-release) and see if the issue is fixed?

Thanks

**Comment by theksepyro** [comment]
Audio plays with it for me first test, so that's good. I'll keep using this version for the next couple days and report back how it goes

**Comment by soncaokim** [comment]
Fyi, the version 1.6.2 released on Play Store contains the same fix as that of the pre-release version.

**Comment by theksepyro** [comment]
So far so good with that pre-release version.

I'll wait until it releases on fdroid though to replace it.

Either way, I'm satisfied enough to call this closed
