### ISSUE TITLE
Broken speaker audio (Test thouroughly before creating a release, perhaps consider creating a beta branch for lower level technical fixes that touch fundamental features)

### ISSUE THREAD

**Issue by secretServant** [VinylMusicPlayer/VinylMusicPlayer#879]
**Describe the bug**
There has now been 3+ releases of broken/half-baked features. 1.5.6 introduced user facing debug spam copied to the clipboard. 1.6.0 broke album pictures. 1.6.1 has now broken native speaker audio. The project will lose support if you keep breaking fundamental user facing features. I appreciate everyone's work but the last couple months of releases have been pretty broken. Please create beta/test/pre-release versions before pushing a new release.

**To reproduce**
Literally can't play audio through speakers, music often refuses to play when starting the app. The whole point of a music app is to play audio files.

**Expected behavior**
Play music.

**Device info**
 - Android Version: Android 13
 - ROM: Lineage
 - Vinyl Music Player Version: 1.6.1

**Comment by soncaokim** [comment]
Hi, I understand your frustration. Are you aware that there is already a pre-release version available for download on the front page of this Github repo https://github.com/VinylMusicPlayer/VinylMusicPlayer? 

Are you willing to use it, and report back here if it fixes your audio issue?

Thanks

**Comment by secretServant** [comment]
I'll wait for a stable release. Doesn't seem like your contributors even test builds on hardware before releasing. As of now there's a plethora of other music players that meet the basic need of playing music, not your users' job to be guinea pigs for months on end.

Basic advice, test your build before releasing as a stable release.

The log spam copied to the clipboard is indicative that this project is heading in the wrong direction. Incompetent and user hostile way to collect error logs, can't share this project with family and friends in good faith anymore.
