### ISSUE TITLE
Adaptive icon for Android 13 and later

### ISSUE THREAD

**Issue by UjuiUjuMandan** [VinylMusicPlayer/VinylMusicPlayer#883]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Draw the icon according to the docs.

**Describe alternatives you've considered**
None.

**Additional context**
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive .

**Comment by soncaokim** [comment]
Duplicate of #635
