### ISSUE TITLE
first track artist being used as album artist (possibly opus related)

### ISSUE THREAD

**Issue by mikelpr** [VinylMusicPlayer/VinylMusicPlayer#894]
**Describe the bug**
lately albums have been showing the first track's artist as the album artist in the grid view instead of the album artist field

**To reproduce**
1. Go to the Albums tab
2. have an album with multiple artists but tagged with the same album artist 

**Expected behavior**
the album artist should come from the album artist tag embedded in the tracks

**Device info**

 - Device: Sony Xperia 1 IV
 - Android Version: 13
 - ROM: stock Sony
 - Vinyl Music Player Version: 1.6.2

**Additional context**
well I noticed that now track numbers from opus files are properly shown (previously, disc 1 track 1 would show as 1001, disc 1 track 2 as 1002, now they show up as 1-1, 1-2, as they should) so I guess there was some logic changes regarding opus tracks tag parsing and possibly had a regression on the album artist part

I don't know if other codecs/containers are impacted

**Comment by soncaokim** [comment]
I dont have multi-track .opus to test with, but the situation regarding Opus tagging support should be improved with #896 (released today). Closing this for now, please dont hesitate to reopen with up-to-date info and a sample .opus file if possible
