### ISSUE TITLE
voice 

### ISSUE THREAD

**Issue by Onehunnidd** [VinylMusicPlayer/VinylMusicPlayer#895]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Close as incomplete.

**Comment by Onehunnidd** [comment]
What do you mean?

**Comment by soncaokim** [comment]
This doesnt provide any description of bug/expected feature. If you have more info to provide, dont hesitate to reopen this issue and give more details.

Happy holidays
