### ISSUE TITLE
Multi genre editor

### ISSUE THREAD

**Issue by gaycodegal** [VinylMusicPlayer/VinylMusicPlayer#914]
To: @gaycodegal 
From: @soncaokim 

"Can you please modify the tag editor screens (per song and per album) so that one can visually modify the genres, in the same model as the artists, ie multi-line text field, one line per genre. The field name/hint should be changed as well to indicate this."

Me again: Will do, moved to a feature request to track.

**Comment by soncaokim** [comment]
HI @gaycodegal 

Have you managed to have some progress on this? If this can be done, I will prep a new release that contains changes from #904 as well. 

Thanks

**Comment by gaycodegal** [comment]
didnt have time to work on it; now do, so starting work. Its not hard work, so should have a PR ready shortly.

**Comment by gaycodegal** [comment]
@soncaokim done, and added #929 as well which i believe should address your concerns of proper SDCard access requesting.

**Comment by soncaokim** [comment]
Fixed by #928
