### ISSUE TITLE
crash on first start new device

### ISSUE THREAD

**Issue by pvoytas** [VinylMusicPlayer/VinylMusicPlayer#918]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Hi, this issue report is to vague - I dont have information on what caused the crash on first start, and hence cannot remediate the situation. Please reopen with more information. Thanks
