### ISSUE TITLE
Crash on app first open and library load

### ISSUE THREAD

**Issue by comfortabletriphazard** [VinylMusicPlayer/VinylMusicPlayer#940]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Close, suspecting this is fixed by #1048 or #1049
