### ISSUE TITLE
Incorrect Notification Style/Category?

### ISSUE THREAD

**Issue by GraphicHealer** [VinylMusicPlayer/VinylMusicPlayer#945]
**Describe the bug**
The notification for music control does not show up correctly. It looks like as shown in the following screenshot.

**To reproduce**
1. Open Vinyl
2. Play Something
3. Pull down notification shade

**Expected behavior**
It should show up as a proper media player notification, like Spotify uses. (See second screenshot)

**Device info**
App version: 1.8.0
App version code: 191
Android build version: 1695680566
Android release version: 13
Android SDK version: 33
Android build ID: TQ3A.230901.001
Device brand: Google
Device manufacturer: Google
Device name: cheetah
Device model: Pixel 7 Pro
Device product name: cheetah
Device hardware name: cheetah
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a] Version:

**Additional context**
Current Vinyl Player Notification
![Screenshot_20240211-091102_Vinyl Music Player~2.png](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/20365116/2422fe9c-094d-4160-b02c-bcc27a62ecc1)

What it should look like (ex: spotify)
![Screenshot_20240211-091437_Spotify~2.png](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/20365116/c3b27433-9f25-4dbe-bc7a-a85e8b73c09e)

**Comment by jeet-74** [comment]
Experiencing same with OP11 running OOS14

**Comment by soncaokim** [comment]
Now for the look:
I assume you have enabled "classic notification design" in the app's Setting screen, havent you?
If it's the case, please disable it - you should have the Spotify look.

**Comment by GraphicHealer** [comment]
![Screenshot_20240226-104716_Vinyl Music Player.png](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/20365116/af810ec4-1599-47ab-8d6c-e2e008283741)

Try that, doesn't work. It just looks worse.

**Comment by GraphicHealer** [comment]
It also does not show up under media player notifications, which I assume would use using the Android media player api, like Spotify does. It seems to just generate a regular notification with some extra buttons.

**Comment by soncaokim** [comment]
The one shown in the 3rd screenshot is from the OS - ie intercepted by the OS via the media player API and rendered in they way the OS/the manufacturer like. 

For instance, I have such ugly notification with my OnePlus with Oxygen OS/Android 14 (3rd screenshot).
On Lineage OS/Android 13, it looks Spotify-styl (2nd screenshot)

However, that's weird/interesting that Spotify manages to circumvent/escape from that.
