### ISSUE TITLE
Launch vinyl and start playing when bluetooth headsets button is pressed.

### ISSUE THREAD

**Issue by shade-belisar** [VinylMusicPlayer/VinylMusicPlayer#948]
**Is your feature request related to a problem? Please describe.**
I often find myself in the situation that I put on my bluetooth headset and would like to start listening to music, but my phone has killed Vinyl. Then I need to unlock my phone, launch the app and finally resume the current playlist.

**Describe the solution you'd like**
I would like vinyl to be launched and the current playlist resumed when I use the media control on my bluetooth headset.

**Describe alternatives you've considered**
Vinyl could keep running at all times, but besides the fact the the now playing notification then unnecessarily blocks part of my notification area, my phone also tends to kill vinyl when it is not actively playing music.

**Additional context**
I tried YouTube Music once and remember that they supported this feature, which is where I got the idea.

**Comment by soncaokim** [comment]
Hi, If Vinyl is running in the background, this is working already (either with bluetooth or wired headset)

And if the OS has killed the app, there isnt much thing we can do. Solution to your request should be on the OS side I'm afraid.
