### ISSUE TITLE
vinyl github ci doesn't work for forked repo?

### ISSUE THREAD

**Issue by tramhao** [VinylMusicPlayer/VinylMusicPlayer#966]
**Describe the bug**
I forked vinyl to add a special function I need. Link is https://github.com/tramhao/VinylMusicPlayer .
My master branch is 100% same with original. However, the build action always fails due to below reason:
```
Run ./script/build-release
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: assembleCiRelease

0 problems were found storing the configuration cache.

See the complete report at file:///home/runner/work/VinylMusicPlayer/VinylMusicPlayer/build/reports/configuration-cache/bmykkrdfkol[20](https://github.com/tramhao/VinylMusicPlayer/actions/runs/8108522830/job/22161893441#step:8:21)ccw6qwor8f6i/1x1qyk1k6rlugrldqd61qw0li/configuration-cache-report.html
Configuration cache entry stored.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/VinylMusicPlayer/VinylMusicPlayer/app/build.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 969ms
Error: Process completed with exit code 1.
```

**To reproduce**
1. Go to Actions
2. Click on 'GithubActions CI'
3. Wait for 30s
4. See above error in "Build CI Application" stage.

**Expected behavior**
It should be successful as my master is 100% same with Vinyl. I even deleted my repo and re-fork it today to test. Same error.

**Device info**
Github.
 - Vinyl Music Player Version: master branch

**Additional context**
By the way, when I build locally in my computer, with key file of myself, I can build successfully.

**Comment by tramhao** [comment]
I checked about 20 forked repos of Vinyl, and they have same problem.

**Comment by soncaokim** [comment]
Looks like the signing config are not set in your Github Actions. I wont be able to help on this, you should investigate with instructions on GH.

**Comment by tramhao** [comment]
Thanks for the direction pointed out. I solve it and want to list here for reference, in case anyone met similar problem.
1. In Github, go to Settings->Security->Secrets and variables
2. Add two repository secrets(not environment variables) named KEYSTORE_PROPERTIES and STORE_FILE.
3. The content of KEYSTORE_PROPERTIES should be similar with root/keystore.propertis, but replace the first line file name with vinyl.jks. The other information can be found in Android Studio.
4. The content of STORE_FILE should be your vinyl.jks file, but base64 encoded with:
openssl base64 < your_signing_keystore.jks | tr -d '\n' | tee your_signing_keystore_base64_encoded.txt

That's all you need to build.

**Comment by soncaokim** [comment]
> I solve it and want to list here for reference, in case anyone met similar problem.

Just for info, I've attempted a change here https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/1057 that would let you avoiding to override the signing config in your cloned repo
